package LiteratureRecommendationSystem.repository;

import LiteratureRecommendationSystem.domain.Literature;
import LiteratureRecommendationSystem.domain.Book;
import LiteratureRecommendationSystem.domain.Manga;
import LiteratureRecommendationSystem.domain.Encyclopedia;

import java.util.function.Supplier;

final class LiteratureRepositorySeed {

    private LiteratureRepositorySeed() {
    }

    static int populate(InMemoryRepository<Literature> repository) {
        int failed = 0;

        //===Book===
        failed += safeAdd(repository, () -> new Book("Detektívka", 6, "Murder in Purple and Gold", "Historická detektívka, ktorej dej sa odohráva v starovekom Ríme na pozadí gladiátorských hier a politických intríg. \nHlavná hrdinka Flávia Albia vyšetruje záhadnú vraždu a postupne odhaľuje nebezpečné tajomstvá vplyvných ľudí mesta.", 2026, "https://www.amazon.com.au/Murder-Purple-Gold-Lindsey-Davis-ebook/dp/B0FNCPSTMS", "Lindsey Davis", 352));
        failed += safeAdd(repository, () -> new Book("Klasika", 6, "Scarlet Morning", "Dobrodružný fantasy román o dvoch deťoch, ktoré sa vydávajú na nebezpečnú cestu morským svetom plným tajomstiev a starých legiend. \nPríbeh spája priateľstvo, prežitie a hľadanie vlastného miesta vo svete po veľkých zmenách.", 2025, "https://www.pantarhei.sk/619763-scarlet-morning-book-1-scarlet-morning-nd-stevenson", "N. D. Stevenson", 432));
        failed += safeAdd(repository, () -> new Book("Román", 6, "The Seaside Sleepover", "Je to príbeh o Daisy, ktorá sa spolu s rodinou a priateľmi vyberie k moru a počas letných prázdnin zažíva svoje prvé samostatné dobrodružstvá. \nKniha rozpráva o priateľstve, rodinnej podpore a radosti zo spoločného času.", 2025, "https://www.amazon.ca/Seaside-Sleepover-Jacqueline-Wilson-ebook/dp/B0CW3W4456", "Jacqueline Wilson", 416));
        failed += safeAdd(repository, () -> new Book("Rozprávka", 6, "The Enchanted Wood", "Rozprávkový príbeh o čarovnom lese, kde sa na vrchole stromu objavujú rôzne magické krajiny. \nKniha rozpráva o detských dobrodružstvách, priateľstve a úžasných stretnutiach vo fantastickom svete.", 2025, "https://cdn.bookey.app/files/pdf/book/en/the-enchanted-wood.pdf", "Enid Blyton", 290));
        failed += safeAdd(repository, () -> new Book("Sci-fi", 6, "Operation Bounce House", "Príbeh o skupine detí, ktoré sa zapoja do nebezpečnej misie spojenej s novými technológiami a vesmírom. \nKniha zdôrazňuje dôležitosť priateľstva, odvahy a tímovej spolupráce.", 2026, "https://www.goodreads.com/book/show/233717212-operation-bounce-house", "Matt Dinniman", 320));
        failed += safeAdd(repository, () -> new Book("Detektívka", 12, "A Beautiful and Terrible Murder", "Historická detektívka zasadená do Oxfordu, kde Irene Adler v prestrojení za študenta vyšetruje sériu vrážd medzi elitou. \nPo boku Sherlocka Holmesa skladá stopy, kým sa z nej samotnej nestane hlavný podozrivý.", 2025, "https://www.barnesandnoble.com/w/a-beautiful-and-terrible-murder-claire-andrews/1146621156", "Claire M. Andrews", 432));
        failed += safeAdd(repository, () -> new Book("Klasika", 12, "Persuasion (First Impressions)", "Klasický román o Anne Elliotovej, ktorá po rokoch znovu stretne kapitána Wentwortha a musí si vybrať medzi rozumom a citom. \nJemný príbeh o druhej šanci ukazuje, ako spoločenský tlak dokáže meniť osudy aj tých najtichších ľudí.", 2025, "https://www.amazon.com/Persuasion-First-Impressions-Jane-Austen-ebook/dp/B0CW1FMS76", "Jane Austen", 320));
        failed += safeAdd(repository, () -> new Book("Román", 12, "Love Me Tomorrow", "Román s jemne magickým nádychom sleduje Emmu, ktorá začne dostávať listy od svojej budúcej lásky naprieč časom. \nKeď sa snaží zistiť, kto jej píše, postupne objavuje, že láska môže byť skutočná aj odvážnejšia, než si myslela.", 2026, "https://www.barnesandnoble.com/w/love-me-tomorrow-emiko-jean/1144629539", "Emiko Jean", 352));
        failed += safeAdd(repository, () -> new Book("Rozprávka", 12, "Angelica and the Bear Prince", "Moderná rozprávka v grafickej podobe rozpráva o Angelice, ktorá sa po vyhorení snaží znovu postaviť na nohy vďaka priateľom a zvláštnemu „medveďovi“ z divadla. \nKeď nastúpi na stáž, aby odhalila, kto sa skrýva pod kostýmom, nájde v sebe odvahu začať odznova.", 2025, "https://www.barnesandnoble.com/w/angelica-and-the-bear-prince-trung-le-nguyen/1146866184", "Trung Le Nguyen", 224));
        failed += safeAdd(repository, () -> new Book("Sci-fi", 12, "Sunrise on the Reaping (A Hunger Games Novel)", "Dystopické sci-fi vracia čitateľa do Panemu v deň Päťdesiatych Hier, keď sú vyžrebovaní dvojnásobní tribúti. \nHaymitch Abernathy bojuje o prežitie aj o to, aby jeho vzdor zaznel ďaleko za hranice arény.", 2025, "https://www.barnesandnoble.com/w/sunrise-on-the-reaping-suzanne-collins/1145703863", "Suzanne Collins", 400));
        failed += safeAdd(repository, () -> new Book("Detektívka", 16, "Final Stop: A British Crime Thriller (DCI Connelly Case Files)", "Policajná detektívka sleduje DCI Connellyovú, keď po ďalšej vražde narazí na sieť spojení, ktoré vedú k ľuďom s veľkým vplyvom. \nPri honbe za pravdou bojuje s mlčaním svedkov a riskuje, že ďalší na rade bude niekto nevinný.", 2025, "https://www.amazon.com/Final-Stop-British-Thriller-Connelly/dp/1916898122", "J M Kennedy", 445));
        failed += safeAdd(repository, () -> new Book("Klasika", 16, "Wuthering Heights: Classics collection edition", "Klasický príbeh o vášnivej láske Catherine a Heathcliffa, ktorá sa v drsnom prostredí yorkshirských vresovísk mení na posadnutosť. \nGenerácie dvoch rodín potom platia cenu za pýchu, žiarlivosť a pomstu, ktorá sa nedá zastaviť.", 2025, "https://www.amazon.com/Wuthering-Heights-collection-Emily-Bront%C3%AB/dp/B0F3JR8WLF", "Emily Brontë", 261));
        failed += safeAdd(repository, () -> new Book("Román", 16, "Summer Fated To Be Mine (The Summer Choice)", "Letný román o dvoch ľuďoch, ktorým sa po rokoch znovu pretne cesta a staré city sa ozvú silnejšie než predtým. \nMedzi plážou, spomienkami a novými rozhodnutiami musia zistiť, či sa dá odpustiť minulosť a vybrať si budúcnosť spolu.", 2025, "https://www.amazon.com/Summer-Fated-Be-Mine-Choice/dp/B0F7GFMR95", "B. Truly", 409));
        failed += safeAdd(repository, () -> new Book("Rozprávka", 16, "The Cinder Rite", "Temné rozprávkové prepracovanie Popolušky mieša fantasy s kozmickým hororom, keď sa pod popolom detských legiend prebudí niečo prastaré a hladné. \nHrdinka sa musí rozhodnúť, či prijme „zázrak“ za cenu vlastnej duše, alebo rozbije kliatbu skôr, než pohltí celý dvor.", 2025, "https://www.amazon.com/Cinder-Rite-Philip-Stengel/dp/B0FCCH3TSF", "Philip Stengel", 131));
        failed += safeAdd(repository, () -> new Book("Sci-fi", 16, "I Am Your Beast: A Science fiction novel", "Akčné sci-fi skúma svet, kde sa telá dajú vyrábať a vedomie zálohovať, no ľudskosť sa stále nedá naprogramovať. \nKeď sa hrdina stane predmetom lovu aj experimentu, musí si vybojovať slobodu a zároveň pochopiť, kým vlastne je.", 2025, "https://www.amazon.com/Am-Your-Beast-Science-fiction/dp/B0F7CG3DTY", "Dexter Mehta", 247));
        failed += safeAdd(repository, () -> new Book("Detektívka", 18, "Dark Sanctuary", "V uzavretej nemocnici pre kriminálne šialených sa začne objavovať séria brutálnych vrážd a seržant Hex Rexford je prinútený počúvať tipy od muža, ktorého kedysi dostal za mreže. \nKeď sa vyšetrovanie prepletie s príbehom matky na úteku a true-crime podcasterov, Hex zistí, že najhoršia hrozba sa pozerá priamo z tmy.", 2026, "https://www.barnesandnoble.com/w/dark-sanctuary-sarah-barrie/1148672499", "Sarah Barrie", 368));
        failed += safeAdd(repository, () -> new Book("Klasika", 18, "A Farewell to Arms", "Klasický román z prvej svetovej vojny sleduje amerického sanitára Frederica Henryho a jeho vzťah s ošetrovateľkou Catherine Barkleyovou uprostred chaosu talianskeho frontu. \nLáska, strach a útek pred nezmyselným násilím sa tu stretávajú s trpkou otázkou, koľko stojí nádej, keď sa svet rúca.", 2025, "https://www.barnesandnoble.com/w/a-farewell-to-arms-ernest-hemingway/1100300814?ean=9780593512951", "Ernest Hemingway", 336));
        failed += safeAdd(repository, () -> new Book("Román", 18, "The Night We Met (Deluxe Edition)", "Larissa sa po jednom osudovom večeri ocitne medzi dvoma priateľmi, kde jeden je „správna“ voľba a druhý zakázaná pravda, ktorú nechce počuť. \nKeď sa tajomstvá začnú valiť na povrch, musí sa rozhodnúť, či zachráni vzťah, alebo konečne prizná, koho naozaj miluje.", 2026, "https://www.barnesandnoble.com/w/the-night-we-met-abby-jimenez/1147826536", "Abby Jimenez", 400));
        failed += safeAdd(repository, () -> new Book("Rozprávka", 18, "Fairy Tale Retellings, Volume I", "Zbierka pikantných romantasy noviel prepisuje známe rozprávky do sveta kliatob, jedov a nebezpečných princov, kde každá dohoda má svoju cenu. \nHrdinky tu bojujú nielen o prežitie, ale aj o vlastnú túžbu, kým sa z „šťastného konca“ nestane hra o moc.", 2025, "https://www.barnesandnoble.com/w/fairy-tale-retellings-volume-i-scarlett-st-clair/1147195838", "Scarlett St. Clair", 464));
        failed += safeAdd(repository, () -> new Book("Sci-fi", 18, "Radiant Star", "V imperialnom svete Radchu sa odľahlé náboženské miesto stane iskrou politických nepokojov, keď jeden muž má byť vybraný na znepokojivú premenu na „živého svätca“. \nUprostred hladomoru, výpadku komunikácie a rastúcej revolty sa osudy troch ľudí zrazia a ukážu, ako rýchlo sa viera mení na zbraň.", 2026, "https://www.barnesandnoble.com/w/radiant-star-ann-leckie/1148171288", "Ann Leckie", 368));
        failed += safeAdd(repository, () -> new Book("Detektívka", 6, "Murdle Jr.: Curious Crimes for Curious Minds", "Štyria mladí detektívi riešia krátke prípady pomocou indícií, kódov a logických mriežok, pričom každý zločin má jedno jasné riešenie. \nKniha podporuje dedukciu, sústredenie a postupné vylučovanie možností, až kým čitateľ neodhalí vinníka.", 2024, "https://www.amazon.com/Murdle-Jr-Curious-Through-Mysteries/dp/0316582557", "G.T. Karber", 240));
        failed += safeAdd(repository, () -> new Book("Klasika", 6, "Big", "Ilustrovaný príbeh o dievčatku, ktoré sa učí prijať samú seba po slovách, ktoré jej ublížili. \nKniha jemne ukazuje deťom dôležitosť sebaúcty a láskavosti.", 2024, "https://www.martinus.sk/2929727-big/kniha", "Vashti Harrison", 60));
        failed += safeAdd(repository, () -> new Book("Román", 6, "The Owlympic Games", "Eva a jej spolužiaci sa pripravujú na školské Owlympijské hry plné pretekov, prekážok a zábavných výziev. \nPopri súťažení sa učia férovosti, tímovej spolupráci a tomu, že skutočné víťazstvo je aj o podpore kamarátov.", 2024, "https://www.barnesandnoble.com/w/the-owlympic-games-rebecca-elliott/1144418603", "Rebecca Elliott", 80));
        failed += safeAdd(repository, () -> new Book("Rozprávka", 6, "Sleeping Beauty", "Kliatba zlej víly uvrhne princeznú do hlbokého spánku a celé kráľovstvo stíchne spolu s ňou. \nKeď po rokoch prichádza odvážny princ, láska a odvaha sa stanú kľúčom k prebudeniu a novému začiatku.", 2023, "https://www.target.com/p/sleeping-beauty-forever-fairy-tales-by-audrey-bea-hardcover/-/A-91542185", "Audrey Bea", 34));
        failed += safeAdd(repository, () -> new Book("Sci-fi", 6, "The Wild Robot", "Robotka Roz stroskotá na opustenom ostrove a musí sa naučiť prežiť v divočine medzi zvieratami a búrkami. \nPostupne si získava dôveru okolia, objaví silu priateľstva a zistí, čo znamená byť súčasťou spoločenstva.", 2024, "https://www.barnesandnoble.com/w/the-wild-robot-peter-brown/1146354980", "Peter Brown", 320));
        failed += safeAdd(repository, () -> new Book("Detektívka", 12, "The Swifts: A Dictionary of Scoundrels", "V rodine Swiftovcov dostane každé dieťa meno z rodinného slovníka a Shenanigan sa odmieta zmieriť s tým, že má byť iba problémová. \nKeď počas zrazu príbuzných niekoho zhodia zo schodov, začne skladať stopy ako detektívka a odhalí, že vrah je bližšie, než si ktokoľvek myslí.", 2024, "https://www.amazon.com/Swifts-Dictionary-Scoundrels-Beth-Lincoln/dp/0593533232", "Beth Lincoln", 352));
        failed += safeAdd(repository, () -> new Book("Klasika", 12, "Alice's Adventures in Wonderland and Through the Looking Glass", "Alica padne do zajačej nory a ocitne sa v svete, kde sa logika obracia naruby a každé stretnutie je hádankou. \nPutovanie cez Zázračnú krajinu aj cez zrkadlo ju naučí rásť, pýtať sa a nestratiť zvedavosť ani medzi bláznivými pravidlami.", 2024, "https://www.quarto.com/books/9780785845461/alice-s-adventures-in-wonderland-and-through-the-looking-glass", "Lewis Carroll", 256));
        failed += safeAdd(repository, () -> new Book("Román", 12, "The Tenth Mistake of Hank Hooperman", "Keď sa Hankova mama nevráti domov, šiestak sa snaží utajiť krízu a postarať sa o malú sestru Boo, kým im dochádza jedlo aj čas. \nHľadanie pomoci ho prinúti čeliť pravde o rodine a zistiť, že druhé šance niekedy prichádzajú v nečakanej podobe.", 2024, "https://www.penguinrandomhouse.com/books/551520/the-tenth-mistake-of-hank-hooperman-by-gennifer-choldenko/", "Gennifer Choldenko", 320));
        failed += safeAdd(repository, () -> new Book("Rozprávka", 12, "Hansel and Gretel", "Hansel a Gretel sa v lese vydajú hľadať jedlo a zablúdia až k domčeku z perníka, ktorý vyzerá ako splnený sen. \nKeď zistia, že za sladkou fasádou číha čarodejnica, musia spojiť odvahu a dôvtip, aby sa dostali domov.", 2024, "https://www.target.com/p/hansel-and-gretel-forever-fairy-tales-by-cecilia-smith-hardcover/-/A-91655447", "Cecilia Smith", 34));
        failed += safeAdd(repository, () -> new Book("Sci-fi", 12, "The Wild Robot Protects", "Robotka Roz žije s ostrovnými zvieratami v pokoji, kým sa pri pobreží neobjaví jedovatá prílivová vlna, ktorá ničí všetko, čoho sa dotkne. \nAby ochránila priateľov aj celý ostrov, musí sa ponoriť do nebezpečenstva, zjednotiť komunitu a nájsť riešenie, ktoré ľudia nikdy nemali vytvoriť.", 2023, "https://www.lbyr.com/titles/peter-brown-2/the-wild-robot-protects/9780316669412/", "Peter Brown", 288));
        failed += safeAdd(repository, () -> new Book("Detektívka", 16, "The Reappearance of Rachel Price", "Bel sleduje dokument o zmiznutí svojej mamy, keď sa Rachel po šestnástich rokoch zrazu objaví a rozbije všetky istoty. \nKeď sa kamery vypnú, Bel začne vyšetrovať nezrovnalosti a odhalí, že návrat môže byť len ďalšia lož.", 2024, "https://www.amazon.com/Reappearance-Rachel-Price-Holly-Jackson/dp/000858219X", "Holly Jackson", 435));
        failed += safeAdd(repository, () -> new Book("Klasika", 16, "Dracula", "Jonathan Harker prichádza do Transylvánie za obchodom, no v hrade grófa Draculu pochopí, že sa stal väzňom nadprirodzenej hrozby. \nZápas o záchranu Miny a Lucy sa mení na hon na upíra, ktorý si do Londýna prináša noc aj nákazu strachu.", 2024, "https://www.amazon.com/Dracula-Chartwell-Deluxe-Editions-Stoker/dp/0785845488", "Bram Stoker", 412));
        failed += safeAdd(repository, () -> new Book("Román", 16, "Check & Mate", "Mallory sa po rokoch vracia k šachu len preto, aby uživila rodinu, no na turnajoch narazí na arogantného šampióna Nolana Sawyera. \nRivalita sa postupne mení na city, zatiaľ čo Mallory bojuje s tlakom médií a vlastnými hranicami.", 2023, "https://www.amazon.com/Check-Mate-Ali-Hazelwood/dp/0593619919", "Ali Hazelwood", 368));
        failed += safeAdd(repository, () -> new Book("Rozprávka", 16, "The Thirteenth Child", "Hazel, krstná dcéra Smrti, sa snaží na kráľovskom dvore liečiť a zároveň splatiť dary, ktoré vždy niečo stoja. \nKeď sa prastaré sľuby začnú lámať, musí si vybrať medzi poslušnosťou osudu a láskou, ktorá môže prekaziť samotnú smrť.", 2024, "https://www.amazon.com/Thirteenth-Child-Erin-Craig/dp/0593482581", "Erin A. Craig", 512));
        failed += safeAdd(repository, () -> new Book("Sci-fi", 16, "In the Lives of Puppets", "Victor žije ukrytý v lese s trojicou robotov, kým nájazd androidov neunesie jeho otca-vynálezcu Giovannia. \nNa ceste do Mesta elektrických snov zistí, že sloboda má cenu a aj stroj môže mať srdce, ktoré sa rozhodne obetovať.", 2023, "https://www.amazon.com/Lives-Puppets-TJ-Klune/dp/125021744X", "T.J. Klune", 432));
        failed += safeAdd(repository, () -> new Book("Detektívka", 18, "The Hunter", "Do ospalej dediny na západe Írska prídu dvaja muži a s nimi aj staré krivdy, ktoré zrazu začnú končiť násilím. \nVyšetrovanie postupne odhaľuje, že najnebezpečnejšie tajomstvá sa skrývajú v tom, čo miestni považujú za „normálne“.", 2024, "https://www.amazon.com/Hunter-Novel-Tana-French/dp/0593493435", "Tana French", 480));
        failed += safeAdd(repository, () -> new Book("Klasika", 18, "The New Life", "Historický román o strete nových myšlienok sexuálnej slobody s konzervatívnou spoločnosťou 19. storočia. \nIntelektuálna a otvorená próza pre dospelých čitateľov", 2024, "https://www.martinus.sk/3071057-the-new-life/kniha", "Tom Crewe", 400));
        failed += safeAdd(repository, () -> new Book("Román", 18, "Happy Place", "Harriet a Wyn sa už rozišli, no pred priateľmi na spoločnej dovolenke predstierajú, že sú stále dokonalý pár. \nMedzi spomienkami a nevypovedanými pravdami zisťujú, že najťažšie je priznať, čo naozaj chcú, keď sa všetko môže znova rozpadnúť.", 2023, "https://www.amazon.com/Happy-Place-Emily-Henry/dp/0593441273", "Emily Henry", 400));
        failed += safeAdd(repository, () -> new Book("Rozprávka", 18, "Apples Dipped in Gold", "Temná rozprávková retelling romanca premieša gotickú atmosféru so zakázanou príťažlivosťou a hrou o moc medzi fae. \nHrdinka musí prežiť intrigy aj kliatby, pričom každý krok k „šťastnému koncu“ ju môže stáť slobodu alebo srdce.", 2024, "https://www.amazon.com/Apples-Dipped-Gold-Fairy-Retelling/dp/1464216886", "Scarlett St. Clair", 240));
        failed += safeAdd(repository, () -> new Book("Sci-fi", 18, "The Ministry of Time", "V blízkej budúcnosti vláda vytvorí tajné ministerstvo, ktoré privádza ľudí z minulosti ako „expatov“ a priraďuje im sprievodcov v súčasnosti. \nKeď sa z pracovného experimentu stane špionážna hra, hrdinka zistí, že čas sa dá ohýbať ľahšie než lojalita a láska.", 2024, "https://www.amazon.com/Ministry-Time-Novel-Kaliane-Bradley/dp/1668045141", "Kaliane Bradley", 352));

        failed += safeAdd(repository, () -> new Book("Detektívka", 6, "A to Z Mysteries: The Absent Author", "Dink, Josh a Ruth Rose sa tešia na stretnutie so slávnym spisovateľom, no keď autor záhadne zmizne, začnú pátrať po stopách v celom meste. \nKrátke kapitoly vedú čitateľa k dedukcii a všímaniu si detailov, kým trojica kamarátov príde na to, čo sa naozaj stalo.", 1997, "https://www.amazon.com/Absent-Author-Z-Mysteries/dp/0679881689", "Ron Roy", 96));
        failed += safeAdd(repository, () -> new Book("Klasika", 6, "The Little Prince", "Malý princ putuje po planétach a stretáva zvláštnych dospelých, ktorí mu ukážu, ako ľahko sa dá zabudnúť na to podstatné. \nJemný príbeh o priateľstve a zodpovednosti pripomína, že najdôležitejšie veci sa často „vidia“ srdcom, nie očami.", 2000, "https://www.amazon.com/Little-Prince-Antoine-Saint-Exup%C3%A9ry/dp/0156012197", "Antoine de Saint-Exupéry", 96));
        failed += safeAdd(repository, () -> new Book("Román", 6, "Junie B. Jones #1: Junie B. Jones and the Stupid Smelly Bus", "Junie B. je šesťročná hrdinka s vlastnou hlavou a rozhodne sa, že na „hlúpy smradľavý“ školský autobus jednoducho nenastúpi. \nJej veselý pohľad na prvé školské dni ukazuje, ako sa dá strach z nového zmeniť na dobrodružstvo plné smiechu.", 1992, "https://www.amazon.com/Junie-Jones-Stupid-Smelly-Bus/dp/0679826424", "Barbara Park", 80));
        failed += safeAdd(repository, () -> new Book("Rozprávka", 6, "Cinderella", "Popoluška žije v tieni macochy, kým jej kúzelná pomoc nedá šancu zažiť večer na bále a veriť vo vlastné sny. \nKeď začne odbíjať polnoc, odvaha a dobré srdce rozhodnú o tom, či sa šťastie dá nájsť aj po jednej stratenej črievičke.", 2014, "https://www.amazon.co.uk/Cinderella-Traditional-Tales-Julia-Jarman/dp/1625215460", "Julia Jarman", 32));
        failed += safeAdd(repository, () -> new Book("Sci-fi", 6, "Midnight on the Moon", "Kúzelný domček prenesie Jacka a Annie na vesmírnu stanicu pri Mesiaci, kde objavia tajomné chodby, prístroje a zvláštne varovania. \nNapäté dobrodružstvo medzi hviezdami spája zvedavosť, odvahu a tímovú spoluprácu, kým deti nájdu cestu späť domov.", 1996, "https://www.amazon.com/Midnight-Moon-Magic-Tree-House/dp/0679863745", "Mary Pope Osborne", 80));




        //===Manga===
        failed += safeAdd(repository, () -> new Manga("Shonen", 12, "One Piece", "dobrodružná manga o pirátovi Luffym, ktorý hľadá legendárny poklad One Piece a sníva stať sa kráľom pirátov", 1997, "https://www.viz.com/shonenjump/chapters/one-piece", "Eiichiro Oda", 106, false));
        failed += safeAdd(repository, () -> new Manga("Shonen", 12, "Naruto", "príbeh mladého ninju Naruta, ktorý sníva stať sa najsilnejším ninja vodcom svojej dediny", 1999, "https://www.viz.com/shonenjump/chapters/naruto", "Masashi Kishimoto", 72, false));
        failed += safeAdd(repository, () -> new Manga("Shonen", 12, "Dragon Ball", "klasická bojová manga o Gokuovi, ktorý trénuje a bojuje proti stále silnejším nepriateľom", 1984, "https://archive.org/details/dragonballvol10000toriyama", "Akira Toriyama", 42, false));
        failed += safeAdd(repository, () -> new Manga("Shonen", 12, "Bleach", "príbeh stredoškoláka Ichiga, ktorý získa schopnosti bojovať proti zlým duchom a chrániť ľudí", 2001, "https://www.viz.com/shonenjump/chapters/bleach", "Tite Kubo", 74, false));
        failed += safeAdd(repository, () -> new Manga("Shonen", 12, "My Hero Academia", "v superhrdinskom svete nasledujeme Izukuho, chlapca bez schopností, ktorý chce stať sa hrdinom", 2014, "https://www.viz.com/shonenjump/chapters/my-hero-academia", "Kohei Horikoshi", 40, false));
        failed += safeAdd(repository, () -> new Manga("Shonen", 14, "Attack on Titan", "v post-apokalyptickom svete ľudstvo bojuje o prežitie proti obrovským humanoidným tvorom zvaným Titáni", 2009, "https://archive.org/details/attackontitan0000isay", "Hajime Isayama", 34, false));
        failed += safeAdd(repository, () -> new Manga("Shonen", 14, "Death Note", "psychologický thriller o študentovi, ktorý objaví zápisník schopný zabíjať ľudí a snaží sa vytvoriť dokonalý svet", 2003, "https://archive.org/details/deathnote0000tsug", "Takeshi Obata", 12, false));
        failed += safeAdd(repository, () -> new Manga("Shonen", 14, "Fullmetal Alchemist", "príbeh dvoch bratov alchymistov, ktorí hľadajú kameň mudrcov aby obnovili svoje telá po zlyhanom experimente", 2001, "https://archive.org/details/fullmetalalchemi0000hiro", "Hiromu Arakawa", 27, false));
        failed += safeAdd(repository, () -> new Manga("Shonen", 14, "Hunter x Hunter", "Gon sa vydáva na cestu stať sa Hunterom a nájsť svojho otca, ktorý je legendárnym Hunterom", 1998, "https://www.viz.com/shonenjump/chapters/hunter-x-hunter", "Yoshihiro Togashi", 37, false));
        failed += safeAdd(repository, () -> new Manga("Shonen", 14, "Demon Slayer", "Tanjiro sa stáva lovecom démonov, aby pomstil svoju rodinu a vyliečil svoju sestru premenenú na démona", 2016, "https://www.viz.com/shonenjump/chapters/demon-slayer-kimetsu-no-yaiba", "Koyoharu Gotouge", 23, false));
        failed += safeAdd(repository, () -> new Manga("Seinen", 16, "Berserk", "temná fantasy manga o Guts-ovi, osamelom mečiarovi, ktorý bojuje proti démonom v brutálnom stredovekom svete", 1989, "https://archive.org/details/berserk0000miur", "Kentaro Miura", 41, false));
        failed += safeAdd(repository, () -> new Manga("Seinen", 16, "Tokyo Ghoul", "Ken Kaneki sa po transplantácii orgánu stáva polovičným ghúlom a musí sa vyrovnať s novou identitou", 2011, "https://archive.org/details/tokyoghoul0000ishida", "Sui Ishida", 14, false));
        failed += safeAdd(repository, () -> new Manga("Seinen", 16, "Monster", "neurochirurg Dr. Tenma loví bývalého pacienta, ktorý sa stal sériovým vrahom, čím sa sám stáva hľadaným", 1994, "https://archive.org/details/monster0000naok", "Naoki Urasawa", 18, false));
        failed += safeAdd(repository, () -> new Manga("Seinen", 16, "Vagabond", "historická manga založená na živote slávneho samuraja Musašiho, ktorý hľadá cestu meča a duchovného rastu", 1998, "https://archive.org/details/vagabond0000inou", "Takehiko Inoue", 37, false));
        failed += safeAdd(repository, () -> new Manga("Seinen", 16, "20th Century Boys", "skupina priateľov z detstva musí čeliť hrozbe tajomného zloducha, ktorý napĺňa ich detské fantázie", 1999, "https://archive.org/details/20thcenturyboys0000uras", "Naoki Urasawa", 22, false));
        failed += safeAdd(repository, () -> new Manga("Shojo", 10, "Sailor Moon", "príbeh Usagi, tínedžerky, ktorá sa transformuje na bojovníčku Sailor Moon a chráni Zem pred zlom", 1991, "https://archive.org/details/sailormoon0000take", "Naoko Takeuchi", 18, false));
        failed += safeAdd(repository, () -> new Manga("Shojo", 10, "Fruits Basket", "Tohru Hondaová objaví tajomstvo rodiny Soma, že sa menia na zvieratá čínskeho zverokruhu, keď ich objíme", 1998, "https://archive.org/details/fruitsbasket0000taka", "Natsuki Takaya", 23, false));
        failed += safeAdd(repository, () -> new Manga("Shojo", 10, "Cardcaptor Sakura", "Sakura objaví magickú knihu a musí zachytiť rozprchnuté karty, aby zachránila svet pred chaosom", 1996, "https://archive.org/details/cardcaptorsakura0000clow", "CLAMP", 12, false));
        failed += safeAdd(repository, () -> new Manga("Shojo", 10, "Nana", "príbeh dvoch mladých žien s rovnakým menom, ktoré sa stretnú v Tokiu a prežívajú lásku, priateľstvo a hudbu", 2000, "https://archive.org/details/nana0000yaza", "Ai Yazawa", 21, false));
        failed += safeAdd(repository, () -> new Manga("Shojo", 10, "Ouran High School Host Club", "Haruci sa zamýli za chlapca a musí pracovať v host klube plnom bohatých a pohľadných študentov", 2002, "https://archive.org/details/ouranhighschoolh0000hatt", "Bisco Hatori", 18, false));
        failed += safeAdd(repository, () -> new Manga("Josei", 18, "Nodame Cantabile", "príbeh dvoch hudobníkov - talentovaného dirigenta Chiakia a excentrickej pianistky Nodame na konzervatóriu", 2001, "https://archive.org/details/nodamecantabile0000nina", "Tomoko Ninomiya", 25, false));
        failed += safeAdd(repository, () -> new Manga("Josei", 18, "Chihayafuru", "Chihaya sa venuje tradičnej japonskej karetné hre karuta a snaží sa stať sa najlepšou hráčkou v Japonsku", 2007, "https://archive.org/details/chihayafuru0000suet", "Yuki Suetsugu", 49, false));
        failed += safeAdd(repository, () -> new Manga("Josei", 18, "Princess Jellyfish", "Tsukimi žije v dome plnom fujoshi, kým nespozná elegantnú Kuranosuke, ktorá má tajomstvo", 2008, "https://archive.org/details/princessjellyfish0000higu", "Akiko Higashimura", 17, false));
        failed += safeAdd(repository, () -> new Manga("Josei", 18, "Honey and Clover", "príbeh umeleckých študentov, ktorí prežívajú prvú lásku, priateľstvo a hľadanie zmyslu života", 2000, "https://archive.org/details/honeyclover0000uimi", "Chica Umino", 10, false));
        failed += safeAdd(repository, () -> new Manga("Josei", 18, "Paradise Kiss", "Yukari sa zapletie so skupinou módnych študentov a objaví svoju vášeň pre modelingu a lásku", 1999, "https://archive.org/details/paradisekiss0000yaza", "Ai Yazawa", 5, false));
        failed += safeAdd(repository, () -> new Manga("Sports", 12, "Slam Dunk", "Hanamichi Sakuragi sa stáva basketbalovým hráčom, aby zapáčil sa dievčaťu, ale objaví vášeň pre šport", 1990, "https://archive.org/details/slamdunk0000inou", "Takehiko Inoue", 31, false));
        failed += safeAdd(repository, () -> new Manga("Sports", 12, "Haikyuu!!", "Hinata, malý hráč volejbalu, sa snaží stať sa najlepším napriek svojej výške a tvorí rivalitu s Kageyamou", 2012, "https://archive.org/details/haikyu0000furu", "Haruichi Furudate", 45, false));
        failed += safeAdd(repository, () -> new Manga("Sports", 12, "Captain Tsubasa", "Tsubasa Ozora je talentovaný futbalista, ktorý sníva stať sa majstrom sveta a vedie svoj tím k víťazstvám", 1981, "https://archive.org/details/captaintsubasa0000taka", "Yoichi Takahashi", 37, false));
        failed += safeAdd(repository, () -> new Manga("Sports", 12, "Kuroko's Basketball", "Kuroko, takmer neviditeľný hráč, spojí sily s talentovaným Kagamim, aby porazili bývalých spoluhráčov", 2008, "https://archive.org/details/kurokosbasketbal0000fuji", "Tadatoshi Fujimaki", 30, false));
        failed += safeAdd(repository, () -> new Manga("Sports", 12, "Hajime no Ippo", "Ippo Makunouchi objaví talent pre box a stúpa v rebríčkoch, aby sa stal šampiónom v ťažkej váhe", 1989, "https://archive.org/details/hajimenoippo0000mori", "George Morikawa", 137, false));

        //===Encyclopedia====
        failed += safeAdd(repository, () -> new Encyclopedia("Astronómia", 12, "Encyklopédia astronómie", "komplexná príručka o vesmíre, hviezdach, planétach a kozmickom priestore s detailnými ilustráciami", 2002, "https://archive.org/details/philipsastronomy00moor", "Patrick Moore", "Vedecká"));
        failed += safeAdd(repository, () -> new Encyclopedia("Biologia", 10, "Encyklopédia biológie", "obsiahla encyklopédia o živých organizmoch, ekosystémoch, bunkovej biológii a evolúcii", 1996, "https://archive.org/details/encyclopedia-of-biology", "Don Rittner", "Prírodovedná"));
        failed += safeAdd(repository, () -> new Encyclopedia("Chémia", 14, "Malá encyklopédia chémie", "slovenská encyklopédia s vyše 3500 heslami o chemických prvkoch, zlúčeninách a procesoch", 1981, "https://archive.org/details/mala-encyklopedia-chemie", "Jaroslav Bína", "Chemická"));
        failed += safeAdd(repository, () -> new Encyclopedia("História", 12, "Encyklopédia svetových dejín", "kompletná encyklopédia pokrývajúca dejiny ľudstva od praveku po súčasnosť", 2011, "https://archive.org/details/encyclopediaofworldhistory_201912", "Alfred J. Andrea", "Historická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Medicína", 16, "De Medicina", "klasická rímska medicínska encyklopédia o diéte, farmakológii a chirurgii z 1. storočia", 47, "https://archive.org/details/de-medicina-celsus", "Aulus Cornelius Celsus", "Medicínska"));
        failed += safeAdd(repository, () -> new Encyclopedia("Fyzika", 14, "Encyklopédia fyziky", "komplexný prehľad fyzikálnych zákonov, teórií a experimentov pre študentov a odborníkov", 1996, "https://archive.org/details/encyclopediaofph00ravi", "Robert M. Besançon", "Fyzikálna"));
        failed += safeAdd(repository, () -> new Encyclopedia("Zoológia", 10, "Encyklopédia zvierat", "ilustrovaná príručka o živočíšnej ríši s fotografiami a informáciami o tisíckach druhov", 2012, "https://archive.org/details/animalsvisualencyclopedia", "DK Publishing", "Biologická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Geografia", 12, "Encyklopédia zemepisu", "komplexný prehľad o kontinentoch, krajinách, mestách a prírodných zdrojoch sveta", 2005, "https://archive.org/details/worldgeographyen0000unse", "Peter Haggett", "Geografická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Technika", 14, "Encyklopédia techniky", "prehľad technologických vynálezov, strojov a priemyselných procesov od praveku po súčasnosť", 2000, "https://archive.org/details/encyclopediaofte00mccu", "Donald Clarke", "Technická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Umenie", 16, "Encyklopédia svetového umenia", "monumentálne dielo pokrývajúce dejiny výtvarného umenia, architektúry a sochárstva", 1996, "https://archive.org/details/encyclopediaofar00myin", "Bernard S. Myers", "Umelecká"));
        failed += safeAdd(repository, () -> new Encyclopedia("Filozofia", 16, "Encyklopédia filozofie", "komplexný prehľad filozofických smerov, mysliteľov a konceptov od antiky po súčasnosť", 2006, "https://archive.org/details/encyclopediaofph00donc", "Donald M. Borchert", "Filozofická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Psychológia", 14, "Encyklopédia psychológie", "obsiahla príručka o psychologických teóriách, metódach a aplikáciách v praxi", 2000, "https://archive.org/details/encyclopediaofps00eysen", "Hans J. Eysenck", "Psychologická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Matematika", 12, "Encyklopédia matematiky", "komplexný prehľad matematických disciplín, teórií a ich aplikácií vo vede a technike", 1988, "https://archive.org/details/encyclopediaofma00grat", "Grattan-Guinness", "Matematická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Literatúra", 14, "Encyklopédia svetovej literatúry", "prehľad literárnych diel, autorov a smerov od antiky po súčasnú literatúru", 1997, "https://archive.org/details/encyclopediaofwo00laza", "Steven R. Serafin", "Literárna"));
        failed += safeAdd(repository, () -> new Encyclopedia("Hudba", 12, "Encyklopédia hudby", "komplexný prehľad hudobných žánrov, skladateľov, interpretov a hudobnej teórie", 2003, "https://archive.org/details/oxfordcompaniont00hoer", "Alison Latham", "Hudobná"));
        failed += safeAdd(repository, () -> new Encyclopedia("Náboženstvo", 16, "Encyklopédia náboženstiev", "obsiahly prehľad svetových náboženstiev, ich histórie, náuky a kultúrneho vplyvu", 2005, "https://archive.org/details/encyclopediaofre00jone", "Lindsay Jones", "Náboženská"));
        failed += safeAdd(repository, () -> new Encyclopedia("Právo", 18, "Encyklopédia práva", "komplexná príručka o právnych systémoch, legislatíve a právnej histórii", 2009, "https://archive.org/details/encyclopediaofam00schul", "David A. Schultz", "Právna"));
        failed += safeAdd(repository, () -> new Encyclopedia("Ekonomika", 16, "Encyklopédia ekonomiky", "prehľad ekonomických teórií, systémov a finančných trhov pre študentov a odborníkov", 2008, "https://archive.org/details/encyclopediaofec00durl", "Steven N. Durlauf", "Ekonomická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Architektúra", 14, "Encyklopédia architektúry", "ilustrovaná príručka o stavebných štýloch, staviteľoch a ikonických budovách sveta", 2008, "https://archive.org/details/encyclopediaofar00cuit", "Cyril M. Harris", "Architektonická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Film", 14, "Encyklopédia filmu", "komplexný prehľad kinematografie, režisérov, hercov a filmových smerov", 2007, "https://archive.org/details/encyclopediaoffi00nash", "Nash", "Filmová"));
        failed += safeAdd(repository, () -> new Encyclopedia("Šport", 10, "Encyklopédia športu", "obsiahla príručka o športových disciplínach, pravidlách, histórii a významných športovcoch", 2003, "https://archive.org/details/encyclopediaofsp00cox", "Michael Cox", "Športová"));
        failed += safeAdd(repository, () -> new Encyclopedia("Astronómia", 8, "Detská encyklopédia vesmíru", "farebná encyklopédia pre deti o vesmíre, planétach a kozmických objavoch s ilustráciami", 2010, "https://archive.org/details/childrensencyclo0000unse", "DK Publishing", "Detská vedecká"));
        failed += safeAdd(repository, () -> new Encyclopedia("Príroda", 8, "Encyklopédia prírody", "ilustrovaná príručka pre deti o rastlinách, zvieratách a prírodných javoch", 2005, "https://archive.org/details/natureencycloped0000unse", "DK Publishing", "Detská prírodovedná"));
        failed += safeAdd(repository, () -> new Encyclopedia("Dinosaurus", 8, "Encyklopédia dinosaurov", "farebná encyklopédia pre mladých čitateľov o dinosauroch a pravekom svete", 2014, "https://archive.org/details/dinosaursencyclo0000unse", "DK Publishing", "Detská paleontologická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Veda", 12, "Encyklopédia vedy", "komplexný prehľad vedeckých disciplín, objavov a technologických inovácií", 2006, "https://archive.org/details/encyclopediaofsc00mchu", "Katherine McMahon", "Vedecká"));
        failed += safeAdd(repository, () -> new Encyclopedia("Vojenstvo", 16, "Encyklopédia vojenských dejín", "prehľad vojenských konfliktov, stratégií, zbraní a významných bitiek v histórii", 2001, "https://archive.org/details/oxfordcompaniont00hola", "Richard Holmes", "Vojenská"));
        failed += safeAdd(repository, () -> new Encyclopedia("Mýtológia", 12, "Encyklopédia mytológie", "prehľad svetových mytológií, bohov, hrdinov a mytologických príbehov", 2004, "https://archive.org/details/encyclopediaofmy00cote", "Arthur Cotterell", "Humanitná"));
        failed += safeAdd(repository, () -> new Encyclopedia("Jazykoveda", 14, "Encyklopédia jazykov", "prehľad svetových jazykov, ich histórie, gramatických štruktúr a lingvistiky", 2006, "https://archive.org/details/encyclopediaofla00ryde", "R.E. Asher", "Jazykovedná"));
        failed += safeAdd(repository, () -> new Encyclopedia("Kuchárska", 10, "Encyklopédia gastronómie", "obsiahla príručka o svetovej kuchyni, ingredienciách a kulinárskych technikách", 2009, "https://archive.org/details/encyclopediaofga0000unse", "Prosper Montagné", "Gastronomická"));
        failed += safeAdd(repository, () -> new Encyclopedia("Zdravie", 14, "Encyklopédia zdravia", "komplexný prehľad o ľudskom tele, chorobách, prevencii a zdravom životnom štýle", 2005, "https://archive.org/details/encyclopediaofhe0000unse", "British Medical Association", "Zdravotnícka"));

        return failed;
    }

    private static int safeAdd(InMemoryRepository<Literature> repository, Supplier<Literature> supplier) {
        try {
            repository.add(supplier.get());
            return 0;
        } catch (RuntimeException ex) {
            System.err.println("Zlyhalo pridanie literatúry do seed-u: " + ex.getMessage());
            return 1;
        }
    }
}